

server:
  port: 9004

spring:
  application:
    name: PAYMENT-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/QuickMallDB_payment
    username: root
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL57InnoDBDialect
    hibernate:
      ddl-auto: update

springfox:
  documentation:
    swagger-ui:
      enabled: true

eureka:
  client:
    fetchRegistry: true

#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka