
server:
  port: 9001

spring:
  application:
    name: QUICK_PRODUCT_SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/QuickMallDB_product
    username: root
    password: 12345
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL57InnoDBDialect
    hibernate:
      ddl-auto: update
#springfox:
#  documentation:
#    swagger-ui:
#      enabled: true